emr/notebook_cluster/main.tf, emr/notebook_cluster/variables.tf, emr_sample/infrastructure.tf
Add an option to provide additional bootstrap actions via `extra_bootstrap_actions` module variable.
The variable defaults to an empty list and is concatenated with the default set in locals, so nothing changes on existing clusters, unless some values are provided.
=> Dynamic bootstrap_action

templates/devops_eks_policy.json
Adds additional permissions to the devops eks policy, necessary for eks cluster networking
=> additional permissions added to devops eks policy - eks networking

emr/notebook_cluster/main.tf, templates/spark_policy.json
EMR bootstrapping only supports bootstrap scripts from S3 buckets. The current way the S3
client within EMR is retrieving the bootstrap scripts causes a failure to retrieve the file in
certain regions.
This change adds logic to the deployment to redirect the bootstrap url to the appropriate region.
=> Add multi-region support to EMR notebook bootstrap

emr/notebook_cluster/main.tf
Follow up to https://github.com/tecton-ai/tecton/commit/11e2aaac835c7d03e8c4e64850afd3849d0d1419
=> Set spark configs to point to the JARs installed during bootstrap

emr/vpc_subnets/subnets.tf, emr/vpc_subnets/variables.tf, emr_sample/infrastructure.tf
Variable `use_existing_vpc` is redundant and is used to configure both VPC and internet gateway while separate vars are passed for VPC ID and IGW ID.
=> Remove redundant EMR flag

emr_sample/outputs.tf
It fails otherwise when deploy_layer is 0 or 1.
=> Only output spark roles when EMR is being set up

databricks_sample/infrastructure.tf, eks/security_groups/main.tf, eks/security_groups/variables.tf, eks/vpc_subnets/outputs.tf, eks/vpc_subnets/subnets.tf, eks/vpc_subnets/variables.tf, emr/vpc_subnets/subnets.tf, emr/vpc_subnets/variables.tf, emr_sample/README.md, emr_sample/infrastructure.tf
- For public NLB we need to whitelist NAT gateway IPs while for private NLB we need to whitelist VPC's CIDR block(s).
- Random nits.
Also:
- Note, TF does not yet have a variable validation that can depend on the other variables.
- Tested by running tecton plan on the fresh account.
- Will replicate this to the Tecton TF repo later.
=> Configure ingress rules to EKS nodes based on public/private NLB

databricks_sample/infrastructure.tf, eks/security_groups/main.tf, eks/security_groups/outputs.tf, eks/security_groups/variables.tf, emr/security_groups/variables.tf, emr_sample/infrastructure.tf, emr_sample/outputs.tf, templates/devops_eks_vpc_endpoint_policy.json, templates/devops_policy_1.json, vpc_deployment/roles.tf, vpc_deployment/variables.tf
**_Note:_** This pull request is into the [`vpc_1`](https://github.com/tecton-ai-ext/tecton-terraform-setup/tree/vpc_1) branch, which is tracking off of the [`vpc_1.0`](https://github.com/tecton-ai-ext/tecton-terraform-setup/releases/tag/vpc_1.0) tag, _not_ the latest from the [`vpc`](https://github.com/tecton-ai-ext/tecton-terraform-setup/tree/vpc) branch. These changes as applied to the latest `vpc` branch can be found in https://github.com/tecton-ai-ext/tecton-terraform-setup/pull/40.
Added resources (security group + IAM policy) which enable the addition of a VPC endpoint within the EKS VPC.
These resources enable the creation of a VPC endpoint within the EKS VPC, which is used for routing traffic to the Tecton cluster appropriately.
This change includes some formatting fixes. Because …
=> [feat][vpc_1] Resources to support EKS VPC endpoint (in own VPC)

emr/notebook_cluster/main.tf
Added eu-west-1 to the supported regions to bootstrap the EMR notebook cluster from.
=> EMR Notebook Cluster: Support boostrapping from eu-west-1

templates/devops_policy_2.json
VPC Deployment: Adding additional es:describe permissions to the devops role as updates to the AWS API (and Terraform) requires these permissions to query state.
=> Adds additional es describe permissions as required by the AWS API

deployment/buckets.tf
Added a new resource `aws_s3_bucket_ownership_controls` which sets the object ownership on the Tecton bucket to `BucketOwnerEnforced`
This is necessary to ensure that files all have the correct uniform permission
=> feat: set bucket acl to BucketOwnerEnforced

databricks_sample/infrastructure.tf, emr_sample/infrastructure.tf, s3/main.tf, s3/variables.tf
Adds the cluster s3 bucket resources
The resource was removed as part of the VPC branch cleanup and never added back. Resource matches that from the master branch [here](https://github.com/tecton-ai-ext/tecton-terraform-setup/blob/master/deployment/buckets.tf).
=> feat: add cluster s3 bucket

deployment/buckets.tf, deployment/variables.tf
Add an option to set tags for offline storage (S3 bucket) inside the `deployment` module using the variable `additional_offline_storage_tags`.
To give an option for Users of the `deployment` module to set proper tags based on the company requirements.
=> feat: add option to set tags for offline storage

emr/debugging/buckets.tf, emr/debugging/variables.tf, emr/notebook_cluster/buckets.tf, emr/notebook_cluster/main.tf, emr/notebook_cluster/outputs.tf, emr_sample/infrastructure.tf, emr_sample/outputs.tf
This will do two things:
- The EMR notebook cluster is now configured by default to have a logs bucket (that Tecton does not have access to)
- When the `emr_debugging` module is enabled, then Tecton is given access to said logs bucket.
A disadvantage here is that the customer will need to grant additional access to the bucket if they want to read the logs. An alternative is to only use that `log_uri` bucket if `emr_debugging` is turned on, but that would force a recreation of the notebook cluster.
=> feat: Enable EMR notebook cluster logs access when debugging enabled 

emr/notebook_cluster/roles.tf, emr_sample/infrastructure.tf
The previous PR #57 didn't give access to the spark role, so the logs bucket was not being populated. This fixes that
=> fix: Give EMR spark role access to notebook cluster logs s3 bucket

databricks_sample/infrastructure.tf, emr_sample/infrastructure.tf, roles/roles.tf, roles/variables.tf, templates/assume_role.json, templates/assume_role_external_id.json
When terraforming VPC deployments, we *need* to use an external ID. This is the error we get:
```
Exception: Customer owned accounts MUST have an external ID. Do not bypass this for security reasons. See https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html
```
We even go as far as to create the external ID, but we don't use it in the assume role policy, and that just adds more manual steps & friction for customers.
This PR automates that.
=> chore: Use external id in the devops role assume policy

emr_sample/outputs.tf
`module.roles` has a count of 1 only if apply_layer > 1, as per the role module definition. We add this check to avoid exceptions.
=> fix: Use apply_layer for role outputs

templates/devops_policy_1.json
DEPLOYMENT_NAME_CONCAT already has a `tecton-` prefix, which makes the name of the loadbalancer `tecton-tecton-<>`
=> fix: Remove extra tecton- prefix from load balancer name

templates/online_ingest_management_policy.json
The `Describe*` API need `resource: ["*"]` because specifying a prefix causes errors when calling these APIs. They also do not have the ability to specify a resource prefix when making the API call.
=> fix: Update permissions needed for management of ingestion api

deployment/buckets.tf
Remove previously added `acl="private"` from the S3 bucket `tecton`.
We can freely remove ACL from the S3 bucket since this bucket does not allow ACLs along with bucket owner enforced.
=> fix: Remove ACL from the S3 bucket `tecton`

templates/eks_policy.json
eks worker role needs an addition to s3 policy to write to log aggregation bucket
=> add eks policy to write logs

databricks_sample/infrastructure.tf, databricks_sample/outputs.tf, emr_sample/infrastructure.tf, emr_sample/outputs.tf, roles/outputs.tf, roles/roles.tf, roles/variables.tf, templates/devops_fargate.json, templates/devops_policy_2.json, templates/fargate_eks_role.json
Update roles that need to be in the ctf to provision access to the fargate resources(i.e delivery stream and the cross account logging permissions.
[Decisions](https://docs.google.com/document/d/16OItHy4D6C9jzvjmxX0jv_4Wqs0ROsXQPj3EvBMf8bM/edit)
=> Add fargate service account roles and policies to allow provisioning of fargate resources

templates/online_ingest_management_policy.json
We need to new permissions to make sure we're cleaning up older versions of the Lambda that are no longer in use.
=> perms: Add permissions to list and delete older lambda versions

templates/online_ingest_management_policy.json
As title, we need some additional permissions to for lambda aliases and target registration/deregistration.
=> fix: Add additional permissions needed for Lambda deployments

databricks_sample/outputs.tf, emr_sample/outputs.tf
Adds the devops role external-id to the outputs
Tecton needs this information in order to leverage the role
=> fix(outputs): add devops role external_id

templates/data_validation_worker_policy.json
The data validation worker needs to put the validation results into Tecton's S3 bucket.
=> [VPC] Allow data validation worker to put objects on S3

emr/notebook_cluster/main.tf, emr/notebook_cluster/variables.tf
- [feat(emr/notebook): allow args to be passed to default bootstrap](https://github.com/tecton-ai-ext/tecton-terraform-setup/commit/eb55815d4f6835258e0d0c8056a5131cf80d379d)
- [fix: true-up bootstrap regions](https://github.com/tecton-ai-ext/tecton-terraform-setup/commit/fe3e7aa88c8ad0acc5de6cdb11cba3210fdb86f0)
- Present in `master` branch, but missing here
=>  feat(emr/notebook): allow args to be passed to default bootstrap

deployment/buckets.tf, deployment/variables.tf, emr/notebook_cluster/main.tf, emr/notebook_cluster/variables.tf
- [feat: tighter controls on bucket encryption/public](https://github.com/tecton-ai-ext/tecton-terraform-setup/commit/7451d3210492ef74473b1673b9f541f1ff18fa55)
- [feat(emr/notebook): allow args to be passed to default bootstrap](https://github.com/tecton-ai-ext/tecton-terraform-setup/commit/458c41af51c3087ad27e5027ea4c16239bac081f)
=> feat: tighter s3 controls + emr/notebook init args

deployment/emr_roles.tf, deployment/variables.tf
Ported from https://github.com/tecton-ai/tecton/pull/11346
Goal: allow our EMR clusters to pull images from ECR to support running
Spark applications with Docker
=> feat: allow EMR roles to pull ECR images

deployment/roles.tf, deployment/variables.tf, deployment/versions.tf, templates/cmk_policy.json
Ported from https://github.com/tecton-ai/tecton/pull/14661
1. Allow customer to specify a kms key by arn and grant permission for spark workers and tecton account to use it for encryption online/offline data store
2. upgrade aws provider version so it supports aws_kms_key_policy resource
test it by spinning up a new deployment and smoke test with granted permissions
=> feat: add support for customer managed kms key

databricks_sample/infrastructure.tf, deployment/roles.tf, deployment/variables.tf, deployment/versions.tf, emr/cross_account/main.tf, emr_sample/infrastructure.tf, privatelink/cross_vpc/variables.tf, scripts/validate-tecton-setup.py, templates/cmk_policy.json
Loosen up aws provider version constraints from ~> 3 to -> 4.60
To incorporate recent aws provider upgrade: https://github.com/tecton-ai/tecton/pull/14661 to support aws_kms_key_policy resource.
=> chore: loosen up aws provider version contraints

emr/security_groups/versions.tf, emr/vpc_subnets/versions.tf
As a result of upgrading Terraform to 1.x, fix `Warning: Reference to undefined provider` due to missing `required_provider` blocks in child modules. This change is already merged in main repo.
=> chore: fix terraform deprecation warning after upgrading to 1.5.7

templates/devops_policy_2.json
Add missing permission `rds:DescribeDBInstances` over resource `arn:aws:rds:*:${ACCOUNT_ID}:db:*` as a result of upgrading to Terraform aws provider v5
test it against `dev-emr-vpc`
=> Aws v5 vpc

deployment/roles.tf
this fix is intended to resolve the error below
```tecton-terraform-setup/databricks_sample> aws-vault exec terraform -- terraform plan 
╷
│ Error: Invalid function argument
│ 
│   on ../deployment/roles.tf line 91, in resource "aws_kms_key_policy" "cmk":
│   91:   policy = templatefile("${path.module}/../templates/cmk_policy.json", {
│   92:     ROLE_ARNS = concat([
│   93:       "arn:aws:iam::${var.account_id}:role/${local.spark_role_name}",
│   94:       "arn:aws:iam::${var.tecton_assuming_account_id}:root",
│   95:     ], var.kms_key_additional_principals)
│   96:   })
│     ├────────────────
│     │ while calling templatefile(path, vars)
│     │ var.account_id is a string
│     │ var.kms_key_additional_principals is a list of string
│     │ var.tecton_assuming_account_id is a string …
```
=> add missed param

roles/satellite.tf
Customers are hitting errors when applying this terraform (see linked ticket). This updates the code to only fetch the output values if they exist, otherwise outputting `null`
Running both `terraform plan` and `terraform validate` locally shows this is valid terraform, which will unblock this issue
[x] No special rollout plan - this change can be reverted if needed.
[ ] Rollout and rollback plan - Please fill this out for backwards-incompatible changes, such as changes to configuration or data models, or changes that need multiple steps to rollout correctly.
https://tecton.atlassian.net/browse/CS-4142
=> fix: outputting s3 values only if they exist

templates/spark_policy.json
We don't need these perms here (in Spark) we only need them in the control plane where we call createtable.
=> Remove unnecessary perms from SparkPolicy

deployment/buckets.tf, deployment/variables.tf
Add the ability to grant read-write s3 access to cross account principals as bucket policy. The main use case is Rift, where the Ray workers running in control plane that cannot get permissions through AssumeRole
Cherrypicked from https://github.com/tecton-ai/tecton/commit/3b8fffc7eadb2b920d0b450b9b08511b81293cee
=> feat: s3 bucket policy to allow cross-account read-write access

databricks_sample/infrastructure.tf, deployment/outputs.tf, deployment/roles.tf, deployment/variables.tf, emr_sample/infrastructure.tf, rift_sample/infrastructure.tf
1. variable rename `use_rift_ca_policy` -> `use_rift_cross_account_policy`
2. Added the code to optionally enable rift for databricks and emr
3. make account id and region consistent across examples.
=> chore: a few tweaks

roles/roles.tf, templates/database_migrator_policy.json
This adds an IAM role and ensuing permissions necessary for running the database migrator. The role is used by the Kubernetes Service Account, while the `db-migrator` pod uses the `tecton-<cluster name>-eks-worker-role` IAM role under the hood. Therefore, the `tecton-<cluster name>-database-migrator` IAM role only needs the assume role policy, but no actual permissions, while the `tecton-<cluster name>-eks-worker-role` IAM role requires the RDS snapshot permissions needed to perform the database migration. The RDS snapshot permissions were based off of the permissions currently used for SaaS clusters. This was successfully tested on an internal cluster.
This PR will not be merged until we begin the rollout plan.
=> Configure DB Migrator IAM role and permissions

databricks_sample/infrastructure.tf, deployment/variables.tf, emr_sample/infrastructure.tf, rift_sample/infrastructure.tf
1. make `s3_read_write_principals` mandatory which in turns enables Rift by default
2. remove `tecton_assuming_account_id` because it we use the default value already.
=> chore: make s3_read_write_principals mandatory

privatelink/cross_vpc/README.md, privatelink/cross_vpc/main.tf, privatelink/cross_vpc/variables.tf
This introduces a `vpc_endpoint_security_group_name` variable, making naming of the underlying security group more flexible. The variable in turn retains the previous hardcoded value as its default to ensure there are no ensuing changes to associated configurations.
This pull request also fixes three minor typos.
This change allows for deployment flexibility.
=> chore: Adds VPC Endpoint Security Group Name Variable

databricks_sample/infrastructure.tf, emr_sample/infrastructure.tf, rift_sample/infrastructure.tf
Make external_id provided by Tecton. There are a few reasons to do this:
1. This smooths out cluster creation process as control plane is created first now
2. Follows the [best practice provided by AWS](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html) that external_id should be provided by the client
=> chore: external_id provided by tecton rep

databricks_sample/outputs.tf, deployment/buckets.tf, emr_sample/outputs.tf, rift_sample/infrastructure.tf, rift_sample/outputs.tf
A couple of bug fixes
1. make sure `kms_key_id` defaults to null
2. Pipe `local.cross_account_external_id` to output
=> fix: add missing local variable

templates/eks_policy.json
Allow eks to call the dynamo import table api. This is in addition to ["135",](https://github.com/tecton-ai/tecton-terraform-setup/pull/135) which adds ImportTable support to vpc deployments.
=> Add emr import table permissions to eks policy

deployment/outputs.tf, deployment/roles.tf, deployment/variables.tf, rift_sample/infrastructure.tf
Previously, we use a single variable `use_rift_cross_account_policy` to toggle between using Rift and Spark compute cross-account policy. This is no longer sufficient after we introduce rift on data plane. Now, we have to differentiate between:
- rift on control plane
- rift on data plane
- spark
This PR introduces to separate flags to control:
1. enablement of rift on control plane: `use_rift_compute_on_control_plane`
2. enablement of spark: `use_spark_compute`
The 4 different combinations of these two flags are:
- #1 on, #2 on: enable both rift on control plane and spark
- #1 on, #2 off: enable rift on control plane
- #1 off, #2 on: enable spark
- #1 off, #2 off: enable rift on data plane (must also include `rift` module)
=> feat: separate flags controlling spark and rift iam resources [DVOPS-1809]

templates/ca_policy.json, templates/rift_ca_policy.json, templates/satellite_ca_policy.json
Also add these missing roles to rift and satellite deployment
=> fix: Update dynamo cross account role with new time to live roles

rift_compute/iam.tf
This change is required to begin spinning up network interfaces for Rift compute jobs at runtime: https://github.com/tecton-ai/tecton/pull/24504
=> Additional permissions to allow creating/deleting network interfaces for Rift VMs

rift_compute/iam.tf
Needed in order to launch Rift instances with Rift's security group rather than the VPC default.
=> Allow ec2:CreateNetworkInterface on Rift's security group

rift_compute/iam.tf, rift_compute/variables.tf
Scope down list of permissions to run Rift on data plane
test on `tecton-dev-ops2` once orchestrator changes are in
=> feat: reduce down the permissions required by Rift VM

rift_compute/iam.tf
Need to allow using this SG so we can migrate orchestrator to it. We can remove the permission to use default SG once the orchestrator change is in.
=> Allow RunInstances on Rift security group

rift_compute/iam.tf
- Allow RunInstances only on NICs that are tagged w/ rift's workflow tag
- Allow RunInstances only on AMIs owned by Amazon and Tecton
=> Adjust Rift permissions for NICs and AMIs

rift_compute/iam.tf
Add the permission to assume into the cross-account intermediary role.
The `rift_compute` module is shared by both Rift-on-control-plane and Rift-on-data-plane. Cross-account intermediary role is used when Rift runs on control plane.
=> feat: support AssumeRole into cross-account intermediate role

rift_compute/outputs.tf
Adding NAT IPs for rift-compute VPC as output here, so they can be incorporated into rules for allowing ingress from rift compute instances to the tecton control plane when restricted-ingress/IP allowlisting is enabled.
Tested with terraform plan in `eshiferax/ip-allowlist-rift` branch of main tecton repo.
=> Add NAT gateway IPs for rift-compute vpc as output list.

rift_compute/iam.tf, rift_compute/variables.tf
(DVOPS-1877) Adding a variable `additional_rift_compute_policy_statements` to allow user to specify a list of IAM statements to be attached to a policy on the rift-compute role.
Test plan output on `tecton-dev-ops-dataplane` pointing to this branch, with the following variable input added to `rift` module (just an example, not actually adding this policy anywhere):
```hcl
module "rift" {
additional_rift_compute_policy_statements = [
{
Effect    = "Allow"
Action    = ["s3:*"]
Resource  = "*"
}
]
}
```
plan output corresponding to this change:
```hcl
+ resource "aws_iam_policy" "additional_rift_compute_policy" {
+ arn         = (known after apply)
+ id          = (known after apply)
+ name        = "tecton-additional-rift-compute-policy"
+ name_prefix = (known after apply)
+ path        = …
```
=> Allow user to specify additional iam policy statements for rift-compute.

rift_compute/iam.tf, rift_compute/variables.tf
In #147, `Allow` rule for `"kms:*"` on `["*"]` was removed as part of scoping down permissions. 
In order for rift compute to be able to access encrypted offline store buckets, the IAM policy needs `"kms:Decrypt", "kms:GenerateDataKey"` for the kms key used to encrypt the offline store. Adding that key's arn as an input variable to the module here `offline_store_kms_key_arn`, and incorporating into the `offline_store_access` policy.
(DVOPS-1879)
=> Take offline store kms key arn as input and add to rift compute policy.

rift_compute/iam.tf
This change makes it so that Rift VMs can only be launched in the Rift security group, not the default Rift VPC group (which has less restrictive rules).
Note: Requires corresponding orchestrator PR to be rolled out to all VM Rift clusters: https://github.com/tecton-ai/tecton/pull/25198
=> Disallow running ec2 instances in the default VPC

rift_compute/main.tf, rift_compute/network_firewall.tf, rift_compute/outputs.tf, rift_compute/variables.tf, rift_compute/vpc.tf, rift_sample/infrastructure.tf
Adding  variable `use_network_firewall` -- this applies DNS-based stateful rules on a network-firewall resource created in the rift VPC. All internet traffic is routed through this firewall before IGW (`private subnet` --> `nat gateway/public subnet` --> `firewall` --> `IGW`). The list of domains are in `local.default_allowed_egress_domains` in `network_firewall.tf`, and can be extended with  `var.additional_allowed_egress_domains`.
Default behavior  (^that variable being `false`) is the same as before (open egress).
Other changes:
* Add output for rift_compute security group ID (needed by control-plane during cluster creation)
* Updated `rift_sample` to include new variables.
Tested with changes in `rift-egress-restrictions-exp` branch on main tecton repo (`dev-zeus`).
=> Add network-firewall option for egress restriction on rift_compute.

rift_sample/infrastructure.tf, rift_sample/outputs.tf
Updating `rift_sample` configuration outputs and syntax.
* Correct s3 logs destination to be ARN rather than just path.
* Correct `outputs` to reference `module.rift[0]` correctly.
=> More rift-sample syntax cleanup.

rift_compute/iam.tf
This change allows compute manager role to retrieve information about EC2 instance types. This permission is necessary for the orchestrator to make informed decisions about instance selection and additional AMI/Docker configuration requirements.
Related orchestrator PR: https://github.com/tecton-ai/tecton/pull/25721
=> Allow ec2:DescribeInstanceTypes for Rift compute manager to better handle non-default instance types

rift_sample/infrastructure.tf
`use_rift_cross_account_policy` on `deployment` module is necessary for both control-plane and data-plane rift configurations (both rely on this role) -- updating `rift_sample` to set this property to true.
=> Set use_rift_cross_account_policy to true for dataplane rift sample.

templates/ca_policy.json, templates/rift_ca_policy.json, templates/satellite_ca_policy.json
This permission will allow Tecton to call ListTagsOfResources in order to determine which tags already exist on a table, to avoid unnecessary tagging operations (which have a low rate limit of 5 QPS across the account).
=> Add ListTagsOfResource permission to Dynamo policies

privatelink/cross_vpc/README.md, privatelink/cross_vpc/versions.tf
The `provider "aws" {}` block is not necessary anymore: ` Earlier versions of Terraform used empty provider blocks ("proxy provider configurations") for child modules to declare their need to be passed a provider configuration by their callers. That approach was ambiguous and is now deprecated.`
Tested by invoking this module from a control-plane tecton TF state + passing in `aws` provider as input, plan worked as expected.
```
module "privatelink" {
providers = {
aws = aws
}
source = "git::https://github.com/tecton-ai/tecton-terraform-setup.git//privatelink/cross_vpc?ref=no-providers-pvtlink-module"
vpc_id                           = module.tecton-saas.kubernetes.vpc_id
vpc_endpoint_service_name        = "com.amazonaws.vpce..."
dns_name                         = "..." …
```
=> Remove redundant providers block from `privatelink/cross_vpc` module

rift_compute/vpc.tf
2 errors happen on terraform plan/apply for users of `rift_compute` who provide a VPC endpoint-service name input (privatelink).
1. Subnet ID reference
```sh
╷
│ Error: Incorrect attribute value type
│ 
│   on .terraform/modules/tecton-saas.rift/rift_compute/vpc.tf line 144, in resource "aws_vpc_endpoint_subnet_association" "tecton_privatelink":
│  144:   subnet_id       = each.value
│     ├────────────────
│     │ each.value is object with 23 attributes
│ 
│ Inappropriate value for attribute "subnet_id": string required.
```
`each.value` here is the subnet resource itself -- we need specifically the `id`.
2.  Private DNS without enabling it on VPC.
```sh
InvalidParameter: Enabling private DNS requires both enableDnsSupport and enableDnsHostnames VPC attributes set to true for 
│   with …
```
=> 2 rift_compute VPC/privatelink fixes: Subnet ID, Private DNS

rift_compute/iam.tf, rift_compute/variables.tf
The flag was used to gate if we should grant permission to m13n worker to access model storage dir. Remove this flag in tf because
1. the dev is completed, and feature is in private review
2. there is cluster level flag to control this feature, so we don't need this flag in tf level any more.
=> Remove custom model flag

templates/ca_policy.json, templates/rift_ca_policy.json
Split S3 bucket permissions into separate, granular policies for GetObject, DeleteObject, and PutObject operations.
- Replaced the broad `S3Object` policy with three specific policies:
- `S3GetObject`: Controls read access to specific S3 paths
- `S3DeleteObject`: Limits delete permissions to offline-store and streaming-checkpoints
- `S3PutObject`: Restricts write access to specific directories
- Added rift-logs specific permissions in the rift policy template
1. Deploy the updated policies to a few internal environment, spanning across different compute types.
2. Verify that:
- Read operations work for all specified paths
- Delete operations only work for offline-store and streaming-checkpoints
- Write operations are successful only for the designated directories
- Rift-specific …
=> feat: fine-grained S3 permissions

rift_compute/variables.tf, rift_compute/vpc.tf, samples/dataplane_rift/README.md, samples/dataplane_rift/infrastructure.tf
Adding a `vpc_cidr` and a `tecton_privatelink_ingress_rules` variable to allow specifying CIDR range and custom ingress rules for the tecton privatelink VPC endpoint within the rift VPC.
Tested with TF plan on `rift-compute-options` branch of tecton repo (`tecton-dev-ops-dataplane`).
=> Add variables for VPC cidr range and custom ingress rules on privatelink endpoint in rift-compute 

rift_compute/main.tf
https://linear.app/tecton/issue/CI-119/narrow-down-ecr-permissions-run-custom-env-tests-on-vm-rift
TLDR: reducing Rift ECR permissions granted to the Tecton control plane down to the minimum required to push images.
=> Narrow down ECR permissions for cross account image uploads

rift_compute/network_firewall.tf
Make some wildcard domains more specific in default allowlist for the network firewall option in rift_compute module.
Reduced to a minimal set for jobs to work (tested in tecton-dev-ops-dataplane).
=> Update egress domain allowlist (rift_compute network firewall)

rift_compute/iam.tf
It is possible that many Rift VM jobs get launched that compete for VCPUs within a customer's account. We want to limit Rift VM job capacity by vCPUs. This PR allows rift cluster managed role to fetch the vcpu service quota
=> allow to fetch vcpu quota for rift jobs

rift_compute/outputs.tf
Add a tf output for the ECR repo arn (previously only had the URL). Useful for referencing in IAM policies.
=> Add output for ECR repo ARN (rift_compute)

emr_sample/infrastructure.tf, emr_sample/outputs.tf, roles/outputs.tf, roles/roles.tf, roles/variables.tf, templates/eks_policy_with_rift.json, templates/offline_store_reader_policy.json
Changes to allow Rift compute to run on deployments set up with the `vpc` model:
Adding an `enable_rift` boolean variable to `roles` module as well as `emr_sample`. If enabled, a different policy file with additional policies for rift (`eks_policy_with_rift.json`) is used. In addition, an 'offline store reader role' is created that can be assumed by the EKS worker and has access to read offline store paths. The following variable inputs are needed with this flag:
* `rift_compute_manager_arn` -- EKS worker role will be allowed to AssumeRole into this role (created separately in `rift_compute` module and passed in as input).
* `rift_ecr_repository_arn` -- EKS worker will be allowed to push to this repo (created separately in `rift_compute` module and passed in as input).
There are also …
=> [vpc] Add support for rift compute on VPC clusters

templates/alb_policy.json, templates/devops_policy_2.json, templates/eks_asg_management.json, templates/fargate_eks_role.json
Added two missing permissions required for launching feature server group.
1. Check out the feature branch from an internal cluster
2. Test `terraform apply` which previously failed due to the missing permissions
3. Expect the apply to pass
=> chore: add missing FSG permissions

templates/devops_eks_policy.json
* Adds needed permissions to be able to create KMS key for EKS secrets encryption
* Tecton requires extra IAM permissions to be able to create the needed KMS key for EKS secrets encryption
=> Fix permission for eks KMS encryption for VPC clusters

templates/devops_eks_policy.json
EKS IAM permissions for VPC devops role does not follow minimum privilege principle. In addition, some permissions (e.g. 'eks:ListClusters') don't support resource scoping and should scope to resource `*`
1. Separate the permissions for EKS cluster and nodegroup
2. Move `eks:ListClusters` permission to `EksGlobal` policy
Test in an internal cluster
=> fix: eks permissions for VPC clusters

rift_compute/iam.tf, rift_compute/variables.tf
Adding optional AWS secret manager access for the Rift compute role to support legacy secret management for some customers
=> Add optional AWS secret manager access for the Rift compute role

samples/controlplane_rift_with_emr/infrastructure.tf
Adding a sample state for control-plane rift and EMR together in the same deployment (tested / worked in a recent deployment).
=> Add a sample state for ctrl-plane rift + dataplane EMR.

databricks_sample/infrastructure.tf
In `databricks_sample`, the reference to the subnets module was incorrect in the `roles` variable, resulting in TF plan failure. Updating to the correct address.
=> Fix module reference in vpc databricks_sample.

.github/workflows/documentation.yaml, .pre-commit-config.yaml, .terraform-docs.yml, deployment/.terraform-docs.yml, deployment/README.md, deployment/outputs.tf, deployment/variables.tf, emr/cross_account/README.md, emr/debugging/README.md, emr/notebook_cluster/README.md, emr/redis/README.md, emr/security_groups/README.md, emr/vpc_subnets/README.md, modules/controlplane_rift/README.md, modules/controlplane_rift/variables.tf, modules/controlplane_rift_with_emr/README.md, modules/databricks/README.md, modules/dataplane_rift/README.md, modules/emr/README.md, modules/standalone_rift/README.md, privatelink/cross_vpc/README.md, rift_compute/.terraform-docs.yml, rift_compute/README.md, rift_compute/outputs.tf, rift_compute/variables.tf
1. Adding [terraform-docs](https://terraform-docs.io/) configuration (taken from [here](https://terraform-docs.io/user-guide/configuration/#options) and modified), pre-commit config,  and Github Action to check that it was run.
* Injects sections into existing readmes if they exist (between `` and ``). To this end, removed the previous manually written input/output sections (from #199) and replaced with these^ placeholders, where terraform-docs added its sections.
2. Updating variable descriptions for `deployment` module.
GH action [ran here](https://github.com/tecton-ai/tecton-terraform-setup/actions/runs/15122900685/job/42509120690) readme changes are included in this PR.
=> Add terraform-docs config and github action.

rift_compute/iam.tf
This folder can be used to pass custom startup scripts to Rift VM jobs, eg to install additional security monitoring applications.
Respective backend PR: https://github.com/tecton-ai/tecton/pull/30978
=> Grant Rift compute nodes permission to read from the bootstrap scripts folder

rift_compute/iam.tf, templates/manage_rift_compute_policy.json, templates/offline_store_access_policy.json, templates/rift_bootstrap_scripts_policy.json, templates/rift_compute_internal_policy.json, templates/rift_compute_logs_policy.json, templates/rift_dynamodb_access_policy.json, templates/rift_ecr_readonly_policy.json, templates/rift_legacy_secrets_manager_access_policy.json
Moving policy definitions for the `tecton-rift-compute` and `tecton-rift-compute-manager` roles out of HCL and into json templates in the `templates/` directory. Tested by using git source reference to this (`templates-iam`) branch and running `terraform plan` on an internal cluster state that uses the `rift_compute` module. Result = "No changes. Your infrastructure matches the configuration."
=> style: Convert rift-compute-manager and rift-compute policies from HCL to json template.

deployment/README.md, deployment/buckets.tf, deployment/roles.tf, deployment/variables.tf, modules/dataplane_rift/README.md, modules/dataplane_rift/infrastructure.tf, modules/dataplane_rift/variables.tf, modules/dataplane_rift_with_emr/README.md, modules/dataplane_rift_with_emr/infrastructure.tf, modules/dataplane_rift_with_emr/variables.tf
Adding two options to `rift_compute` module: 
1. `controlplane_access_only` -- When `true`, this removes legacy `153453085158` account from trust policy for cross-account role. This works for all newer accounts that only rely on access from roles in the control-plane account directly.
2. `include_crossaccount_bucket_access` -- When `true`, does _not_ add bucket policy to offline-store bucket for direct cross-account access. This is OK for dataplane Rift, where all access to the offline-store will come through the assumed role in dataplane. [Reference](https://tectonworkspace.slack.com/archives/C08D8QRLEEP/p1745257752620189?thread_ts=1745255476.126599&cid=C08D8QRLEEP)
Setting defaults for both of these appropriately in `dataplane_rift` and `dataplane_rift_with_emr` module. Control plane …
=> feat: Add options for disabling direct cross-account bucket policy and limiting cross-account assumerole

deployment/roles.tf
This is necessary in anticipation of ConfigurationChecks (from Deployment Scorecard) verifying that the cross-account role can perform various actions (e.g.: ECR image upload/download).
Reviewers: Please let me know what level of testing you'd like to see for this change.
ref FOUND-493
=> Ensure that dataplane cross-account role can perform SimulatePrincipalPolicy

deployment/roles.tf, rift_compute/main.tf
When we enabled use of cross-account-ecr on dev rift, it failed due to unavailability of ecr:GetAuthorizationToken. This PR allow-lists that action.
ref FOUND-484
=> Add ecr:GetAuthorizationToken to permitted actions
