emr/notebook_cluster/main.tf
emr/notebook_cluster/variables.tf

Allow settings instance count as well as EBS type, size, and count via variables.
Also fixed a minor alignment issue in base_config.

Parameterize EMR EBS configuration

---

databricks_sample/infrastructure.tf
emr_sample/infrastructure.tf

Pass in AZ count to the modules

---

templates/devops_eks_policy.json

Needed to add nodes / change node type

Update EKS policy to allow us to update cluster

---

emr/vpc_subnets/subnets.tf

Replicating https://github.com/tecton-ai-ext/tecton-terraform-setup/commit/a7c19061d4aefdfedc90983ba6961d3f55d5abb1 from the VPC branch.

Remove tecton from the public subnet name

---

databricks_sample/outputs.tf
emr_sample/outputs.tf
roles/outputs.tf
roles/roles.tf
templates/devops_policy_1.json

- Adds role outputs to sample infra.tf files
- Fixes invalid character in policy template
These are necessary for Tecton to deploy

[vpc] Add role outputs to samples

---

emr/notebook_cluster/outputs.tf
emr_sample/infrastructure.tf
emr_sample/outputs.tf

Adds the EMR notebook cluster ID output to the EMR sample
As requested

add emr notebook cluster id output

---

templates/online_ingest_management_policy.json

fix: remove extra comma and remove newline

---

roles/roles.tf

fix: Rename online ingest role to match internal pattern

---

templates/devops_ingest_policy.json

fix: Allow listing role policies for ingest api

---

templates/devops_fargate.json

Signed-off-by: Kevin Zhang <kzhang@tecton.ai>

Add fix to oidc provider perms

---

templates/devops_ingest_policy.json
templates/online_ingest_management_policy.json
templates/online_ingest_role.json

feat: Add permissions for Ingest API to manage offline logging DLQ

---

templates/cross_account_databricks.json

fix(db-cross-account-role): add dynamo GetItem

---

roles/roles.tf
roles/satellite.tf
templates/eks_policy.json

I forget that needs to add fargate eks role to worker role in the main region. This is verified in dev-emr-vpc us-east-2 region.

Add fargate eks role to node role

---

templates/online_ingest_management_policy.json

fix: Move ALB permission to be more constrained

---

templates/devops_fargate.json

Add iam:ListRolePolicies to devops role as part of fargate migration we created the inline policy here 
https://github.com/tecton-ai/tecton/blob/2d49602dac415c6bc4aa2af7c304db206d0e8dfc/infrastructure/deployment/modules/roles/main.tf#L172
and 
https://github.com/tecton-ai/tecton/blob/92d29ea79724e6e2709516850bc8ee0985008396/infrastructure/deployment/modules/satellite/main.tf#L214

add iam:ListRolePolicies

---

templates/emr_ca_policy.json

EMR will require this in addition to RunJobFlow on April 24th

[emr] addtags for vpc

---

templates/ca_policy.json

Adds `iam:ListRolePolicies` to ca_policy, should the policies be in-line

Add iam:ListRolePolicies to ca_policy

---

deployment/buckets.tf

Ported from https://github.com/tecton-ai/tecton/pull/14692
Remove bucket acl so it stops conflicting with OwnerEnforced bucket ownership

chore: remove bucket acl

---

emr/cross_account/main.tf
emr_sample/infrastructure.tf
privatelink/cross_vpc/variables.tf
scripts/validate-tecton-setup.py

Update the docs link to the latest, Ported from https://github.com/tecton-ai/tecton/pull/14660

docs: update the docs link to the latest version

---

deployment/buckets.tf

Refactor offline s3 bucket policy to using `aws_iam_policy_document` data resource so that we can add different dynamic statements to it with their own conditions. This is the prerequsite to enable the cross-account S3 access from Rift control plane.
Cherrypicked from https://github.com/tecton-ai/tecton/commit/46503c0628673c3fd750c10857888707705e742c

refactor: offline store s3 bucket policy

---

databricks_sample/outputs.tf
deployment/outputs.tf
deployment/roles.tf
emr_sample/outputs.tf
rift_sample/outputs.tf

Make sure KMS key works with Rift
Deploy it to a test cluster

feat: fully support KMS on rift

---

databricks_sample/infrastructure.tf
emr_sample/infrastructure.tf
rift_sample/infrastructure.tf
templates/ca_policy.json

- Update Terraform samples to reflect new assuming account defaults. 
- Sync w/ monorepo

chore: update CFT samples, sync monorepo

---

databricks_sample/infrastructure.tf
eks/vpc_subnets/subnets.tf
emr_sample/infrastructure.tf
roles/roles.tf
roles/variables.tf
templates/alb_policy.json

-    Add permissions for AWS ALB Controller, its deployment, and management
-    Update Terraform samples

chore: update CFT samples, add alb functionality for VPC branch

---

deployment/roles.tf
deployment/variables.tf

Port over https://github.com/tecton-ai/tecton/pull/21433

chore: port changes from mono repo copy

---

rift_compute/iam.tf

Fix CreateNetworkInterface policy for Rift

---

README.md
rift_sample/README.md
rift_sample/infrastructure.tf
rift_sample/outputs.tf

Updating `rift_sample` configuration:
*  Added readme
* Fixed a couple variables/inputs (pointing to correct module path, using correct spelling for locals variable, and valid list of example AZs).
* Add all outputs from rift_compute module

Fix variables in rift_sample + add readme.

---

templates/ca_policy.json
templates/eks_policy.json
templates/satellite_ca_policy.json

CP of https://github.com/tecton-ai/tecton-terraform-setup/commit/7f7c91e81c5986f96a9d69892b23afcd3d96eba6

Add ListTagsOfResource permission to Dynamo policies for VPC branch

---

rift_compute/iam.tf
rift_compute/variables.tf

Reverts tecton-ai/tecton-terraform-setup#172
Due to [breakage in TF test](https://buildkite.com/tecton/internal-usage-only-run-terraform-plan-pipeline/builds/7842#0194ae5b-2c6b-464c-961a-1d1a5d1606f8)

Revert "Remove custom model flag"

---

rift_compute/iam.tf
rift_compute/variables.tf

Reverts tecton-ai/tecton-terraform-setup#174
Safe to remove now that it is removed from dev-shared here https://github.com/tecton-ai/tecton/pull/28052

Revert "Revert "Remove custom model flag""

---

templates/devops_eks_policy.json
templates/devops_policy_1.json

- add permissions to devops role to apply encryption to EKS
- add permissions to devops role to apply ALB changes

chore: add permissions to devops role to apply kms encryption for eks

---

.github/workflows/release.yaml

Adding [release-please](https://github.com/googleapis/release-please) github workflow to write changelog and tag releases.

Add release-please github action.

---

deployment/roles.tf

Ensure cross-account role can perform ECR actions

---

deployment/roles.tf

Ensure the ecr action list is properly aligned between role-permissions and ECR policy
